robot: panda
data:
  dataset_name: dream
  batch_size: 35
  s2r_batch_size: 16
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: dream
  num_workers: 16
  pin_mem: true
  root_path: data/  #TODO: change to your data path
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
  pre_computed_bbox: true
  test_seq: real/panda-3cam_realsense #choose from synthetic/panda_synth_test_photo, synthetic/panda_synth_test_dr, or real/panda-3cam_azure, real/panda-3cam_kinect360, real/panda-3cam_realsense, and real/panda-orb
  s2r_seq: real/panda-3cam_realsense #choose from real/panda-3cam_realsense, real/panda-3cam_azure, real/panda-3cam_kinect360, and real/panda-orb
  checkpoint_name: robopepp_ssl_realsense.pt
model:
  backbone: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  jepa_path : /data/raktim/Projects/JEPA/ijepa/logs/jepa_joints-ep200.pth.tar #TODO: change to your ijepa path
  patch_size : 16
  image_shape : 224
  urdf_file: urdfs/Panda/panda.urdf #TODO: change to your urdf path
training:
  epochs: 200
  s2r_epochs: 10
  use_accelerate: true
  log_wandb: false
  max_lr: [1e-4, 1e-4, 1e-4, 1e-4]
  weight_decay: 1e-7
  final_div_factor: 1e4


